spring:
  config:
    activate:
      on-profile: prod

wx:
  auth:
    mock-enabled: false

app:
  security:
    expose-docs: false
  health:
    huawei:
      mock-enabled: false
  file-storage:
    public-read: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    cn.miyf: INFO
    root: WARN
